name = "aiken-lang/zklogin"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/zklogin'"

[repository]
user = "aiken-lang"
project = "zklogin"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "modulo-p/ak-381"
version = "v0.1"
source = "github"

[config]
